version: '3.5'

services:

  gateway:
    ports:
      - 8080:8080
    image: functions/gateway:0.7.9
    networks:
      - functions
    environment:
      functions_provider_url: 'http://faas-swarm:8080/'
      read_timeout:  '25s'
      write_timeout: '25s'
      upstream_timeout: '20s'
      dnsrr: 'true'
      direct_functions: 'true'
      direct_functions_suffix: ''
    deploy:
      resources:
        reservations:
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 380s
      placement:
        constraints:
          - 'node.platform.os == linux'

  faas-swarm:
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    image:  functions/faas-swarm:0.2.3
    networks:
      - functions
    environment:
      read_timeout:  '25s'
      write_timeout: '25s'
      DOCKER_API_VERSION: '1.30'
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
          - 'node.platform.os == linux'
      resources:
        reservations:
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 380s

  eval:
    image: python-eval:latest
    labels:
      function: 'true'
    networks:
      - functions
    environment:
      no_proxy: 'gateway'
      https_proxy: $https_proxy
    deploy:
      placement:
        constraints:
          - 'node.platform.os == linux'

  ping:
    image: python-ping:latest
    labels:
      function: 'true'
    networks:
      - functions
    environment:
      no_proxy: 'gateway'
      https_proxy: $https_proxy
    deploy:
      placement:
        constraints:
          - 'node.platform.os == linux'

networks:
  functions:
    driver: overlay
    attachable: true
    labels:
      - 'openfaas=true'
